# Generated by Django 5.1.7 on 2025-03-15 15:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='limite',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='gasto', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para tracking de la transferencia', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=15)),
                ('referencia', models.CharField(blank=True, help_text='Código de referencia para la transferencia', max_length=50, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, help_text='Código de respuesta de la API bancaria', max_length=50, null=True)),
                ('mensaje_respuesta', models.TextField(blank=True, help_text='Mensaje de respuesta de la API bancaria', null=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
