# Generated by Django 5.1.15 on 2026-02-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sanitize_invalid_financial_rows(apps, schema_editor):
    Transaccion = apps.get_model("finanzas", "Transaccion")
    Transferencia = apps.get_model("finanzas", "Transferencia")

    # Idempotent cleanup before enforcing DB constraints.
    Transaccion.objects.filter(monto__lte=0).delete()
    Transferencia.objects.filter(monto__lte=0).delete()
    Transferencia.objects.filter(emisor_id=models.F("receptor_id")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_alter_categoria_options_remove_categoria_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "monto_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad máxima a gastar en esta categoría",
                        max_digits=10,
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        help_text="Mes del presupuesto (1-12)",
                    ),
                ),
                ("año", models.IntegerField(help_text="Año del presupuesto")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="finanzas.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-año", "-mes", "categoria__nombre"],
                "unique_together": {("usuario", "categoria", "mes", "año")},
            },
        ),
        migrations.RunPython(
            code=sanitize_invalid_financial_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="transaccion",
            constraint=models.CheckConstraint(
                check=models.Q(monto__gt=0),
                name="transaccion_monto_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferencia",
            constraint=models.CheckConstraint(
                check=models.Q(monto__gt=0),
                name="transferencia_monto_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferencia",
            constraint=models.CheckConstraint(
                check=~models.Q(emisor=models.F("receptor")),
                name="transferencia_emisor_receptor_diferentes",
            ),
        ),
    ]

