# Generated by Django 5.1.15 on 2026-02-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_restore_presupuesto_and_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfilusuario",
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
